SWIN_CONFIG = {
    "network_type": "Swin",
    "pretrained": False,
    "image_size": 128,
    "batch_size": 32,
    "num_epochs": 15,
    "optimizer_config": {
        "name": "AdamW",
        "weight_decay": 0.01,
        "lr": 0.001,
        "momentum": 0.9,
        "betas": (0.9, 0.999),
        "warmup_epoch": 3,
    },
    "lr_schedule_config": {
        "use_lr_schedule": True,
        "step_lr": {"gamma": 0.5, "step_size": 20,},
        "reduce_on_plateau": {
            "factor": 0.1,
            "patience": 4,
            "threshold": 0.0000001,
            "verbose": True,
        },
    },
    "channels": 1,
    "network_config": {
        "patch_size": 4,
        "window_size": 4,
        "embed_dim": 96,
        "in_chans": 1,
        "drop_path_rate": 0.1,
        "depths": (2, 2, 2, 2),
        "num_heads": (3, 2, 2, 2),
    },
}
